# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GWRKt7yBC5tT9iemlxJnCrNEyqOfN_k
"""

# Operações matemáticas básicas
print('Olá! Vamos começar com a calculadora?')

# Escolha da operação
operacao = input('Digite a operação desejada: ')

if operacao not in ['+', '-', '*', '/']:
  while True:
    operacao = input('Operação inválida. Por favor, escolha entre +, -, *, /.\n')
    if operacao in ['+', '-', '*', '/']:
      break

# Escolha dos números
if operacao in ['+', '-', '*', '/']:
  while True:
    try:
      num1 = int(input('Digite o primeiro número: '))
    except ValueError:
      print('Comando Inválido. Por favor digite apenas números inteiros.')
    else:
        break
  while True:
    try:
      num2 = int(input('Digite o segundo número: '))
    except ValueError:
        print('Comando Inválido. Por favor digite apenas números inteiros.')
    else:
        break

soma = num1 + num2
subtracao = num1 - num2
multiplicacao = num1 * num2
divisao = num1 / num2

if operacao == '+':
  print(num1, '+', num2, '=', soma)
  print('\n')
elif operacao == '-':
  print(num1, '-', num2, '=', subtracao)
  print('\n')
elif operacao == '*':
  print(num1, '*', num2, '=', multiplicacao)
  print('\n')
elif operacao == '/':
  print(num1, '/', num2, '=', divisao)
  print('\n')

# Maior, menor ou igual
print('Vamos descorir se um número é maior, menor ou igual a outro?')

while True:
  try:
    num1 = int(input('Digite o primeiro número: '))
    break
  except ValueError:
    print('Comando Inválido. Por favor digite apenas números inteiros.')
    num1 = int(input('Digite o primeiro número: '))
    break
while True:
  try:
    num2 = int(input('Digite o segundo número: '))
    break
  except ValueError:
    print('Comando Inválido. Por favor digite apenas números inteiros.')
    num2 = int(input('Digite o segundo número: '))
print('\n')

if num1 > num2:
  print(num1, 'é maior que', num2)
elif num1 < num2:
  print(num1, 'é menor que', num2)
else:
  print(num1, 'é igual a', num2)
print('\n')

# Verdadeiro ou Falso
print('Vamos descobrir se a afirmação é verdadeira ou falsa?')
print('A ordem dos fatores não altera o resultado')

while True:
  try:
    num1 = int(input('Digite o primeiro número: '))
    break
  except ValueError:
    print('Comando Inválido. Por favor digite apenas números inteiros.')
    num1 = int(input('Digite o primeiro número: '))
while True:
  try:
    num2 = int(input('Digite o segundo número: '))
    break
  except ValueError:
    print('Comando Inválido. Por favor digite apenas números inteiros.')
print('\n')

operacao = {
    '+': lambda x, y: x + y,
    '-': lambda x, y: x - y,
    '*': lambda x, y: x * y,
    '/': lambda x, y: x / y
}

for simbolo, operacao in operacao.items():
  if operacao(num1, num2) == operacao(num2, num1):
    print(f'{num1} {simbolo} {num2} é igual a {num2} {simbolo} {num1}')
    print('A afirmação é verdadeira, a ordem dos fatores não altera o resultado\n')
  else:
    print(f'{num1} {simbolo} {num2} é diferente de {num2} {simbolo} {num1}')
    print('A afirmação é falsa, a ordem dos fatores altera o resultado\n')

print('\n')
print('Obrigado por usar a calculadora!')
print('\n')